name: AWS CDK deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CDK
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.14"
      - name: setup dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: unit tests
        run: npm run test
      - name: CDK diff check
        run: npx cdk diff --context targetEnvironment=production
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: CDK deploy
        run: npx cdk deploy --context targetEnvironment=production --outputs-file ./cdk-outputs.json --all --require-approval never
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
